name: 'Evaluator installer'
description: 'Install the policy evaluator'
runs:
  using: "composite"
  steps:
    - name: Install the slsa-verifier
      uses: slsa-framework/slsa-verifier/actions/installer@eb7007070baa04976cb9e25a0d8034f8db030a86 # v2.5.1

    - name: Create tmp dir
      id: working_dir
      shell: bash
      run: |
        set -euo pipefail
        working_dir=$(mktemp -d)
        echo "name=${working_dir}" >> "$GITHUB_OUTPUT"

    - name: Debug
      shell: bash
      working-directory: ${{ steps.working_dir.outputs.name }}
      env:
        # See https://docs.github.com/en/actions/learn-github-actions/contexts.
        GH_ACTION_REF: ${{ github.action_ref }}
        GH_ACTION_REPOSITORY: ${{ github.action_repository }}
      run: |
        echo "GH_ACTION_REF: ${GH_ACTION_REF}"
        echo "GH_ACTION_REPOSITORY: ${GH_ACTION_REPOSITORY}"
        echo "PWD: $PWD"

    - name: Download the publish binary
      id: download
      shell: bash
      working-directory: ${{ steps.working_dir.outputs.name }}
      env:
        GH_ACTION_REF: ${{ github.action_ref }}
        GH_ACTION_REPOSITORY: ${{ github.action_repository }}
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail

        # TODO(21): Support commit sha.
        sha=$(echo -n "${GH_ACTION_REF}" | grep -o -E -e "^[a-f0-9]{40}$" || true)
        if [[ -n "${sha}" ]]; then
          echo "${GH_ACTION_REF} not supported"
          exit 1
        fi
        ref="${GH_ACTION_REF}"
        gh release -R "${GH_ACTION_REPOSITORY}" download "${ref}" -p "binary-linux-amd64*"
        chmod u+x binary-linux-amd64
        echo "ref=${ref}" >> "$GITHUB_OUTPUT"

    - name: Verify the binary
      shell: bash
      working-directory: ${{ steps.working_dir.outputs.name }}
      env:
        GH_ACTION_REF: ${{ steps.download.outputs.ref }}
      run: |
        set -euo pipefail
        slsa-verifier verify-artifact binary-linux-amd64 --provenance-path binary-linux-amd64.intoto.jsonl --source-uri github.com/laurentsimon/slsa-policy --source-tag "${GH_ACTION_REF}"

    - name: Add binary to path
      shell: bash
      working-directory: ${{ steps.working_dir.outputs.name }}
      env:
        GH_ACTION_REF: ${{ steps.download.outputs.ref }}
      run: |
        set -euo pipefail
        mkdir -p "${HOME}/.slsa/bin/${GH_ACTION_REF}"
        mv binary-linux-amd64 "${HOME}/.slsa/bin/${GH_ACTION_REF}/slsa-policy"
        echo "${HOME}/.slsa/bin/${GH_ACTION_REF}" >> $GITHUB_PATH
